image: openjdk:17-jdk-alpine

stages:
  - build

build_job:
  stage: ßbuild
  script:
    - apk update
    - apk add "apache-ant>1.10"
    - java -version
    - ant -version
    - ant
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always